version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: DockerCRUD
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  spring-boot-app:
    image: docker_crud
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/DockerCRUD
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "root"

volumes:
  mysql_data:




